---
aws:
  access_key_id: ...
  secret_access_key: ...
  region: us-east-1
name: dev102
vpc:
  domain: dev102.cf.com
  instance_tenancy: default
  cidr: 10.10.0.0/16
  subnets:
    bosh:
      cidr: 10.10.0.0/24
      availability_zone: us-east-1a
    cf:
      cidr: 10.10.1.0/24
      availability_zone: us-east-1a
    cf_az2:
      cidr: 10.10.2.0/24
      availability_zone: us-east-1b
  dhcp_options:
    domain_name: dev102.cf.com
    domain_name_servers:
      - 10.10.0.6
      - 172.16.0.23
  security_groups:
    - name: open
      ingress:
        - protocol: tcp
          ports: 0 - 65535
          sources: 0.0.0.0/0
        - protocol: udp
          ports: 0 - 65535
          sources: 0.0.0.0/0
    - name: ssh
      ingress:
        - protocol: tcp
          ports: 22
          sources: 0.0.0.0/0
elastic_ips:
  router:
    instances: 2
    dns_record: "*"
  micro:
    instances: 1
    dns_record: micro
key_pairs:
  dev102: /tmp/somekey
rds:
  - instance: ccdb
    tag: cc
    subnets:
      - cf_rds1
      - cf_rds2
    aws_creation_options:
      db_instance_class: db.m2.x4.large
      allocated_storage: 7
  - instance: uaadb
    tag: uaa
    subnets:
      - cf_rds1
      - cf_rds2
