---
platform: linux

inputs:
- name: environment
- name: bosh-ci
- name: bosh-cli
- name: bosh-deployment
- name: bosh-release
- name: stemcell
- name: director-state
  optional: true # chain tasks for upgrades

caches:
- path: cache-dot-bosh-dir

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""

outputs:
- name: director-state

run:
  path: bosh-ci/ci/bats/tasks/deploy-director.sh
