---
platform: linux

inputs:
- name: director-state
- name: bosh-ci
- name: bosh-cli
- name: stemcell
- name: zookeeper-release
- name: bosh-deployment

run:
  path: bosh-ci/ci/tasks/deploy-zookeeper.sh

params:
  CPI:
