---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-master-with-final
  - name: version

outputs:
  - name: bosh-master-bumped-dev-version

run:
  path: bosh-src/ci/tasks/patch-to-dev.sh
