---
platform: linux

inputs:
  - name: bosh-ci
  - name: bosh-ci-dockerfiles
  - name: bosh-deployment

run:
  path: bosh-ci/ci/tasks/prepare-build-context-for-container-cpi-image.sh

params:
  CONTAINER_CPI_TYPE:

outputs:
  - name: docker-build-context

