---
platform: linux

image: docker:///bosh/main

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/publish-coverage.sh

params:
  CODECLIMATE_REPO_TOKEN: replace-me
  RUBY_VERSION:           2.1.7
