---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource

inputs:
- name: candidate-version
- name: bosh-src
- name: metalink-path
- name: compiled-release

params:
  AWS_ACCESS_KEY_ID: ~
  AWS_SECRET_ACCESS_KEY: ~
  AWS_ROLE_ARN: ~
  git_private_key: ~

run:
  path: bosh-src/ci/tasks/push-bosh-compiled-release.sh
