---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src

run:
  path: bosh-src/ci/tasks/run.sh

params:
  RUBY_VERSION: replace-me
  COMMAND: "echo command"
