---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5

inputs:
  - name: bosh-src
  - name: candidate-release
  - name: bosh-deployment
  - name: bbl-state
  - name: stemcell
  - name: zookeeper-release
  - name: prometheus-boshrelease

outputs:
  - name: updated-bbl-state

params:
  BBL_GCP_SERVICE_ACCOUNT_KEY: ""
  BBL_GCP_REGION: ""
  BBL_IAAS: gcp
  BBL_STATE_DIR: ""

run:
  path: bosh-src/ci/tasks/setup-env.sh
