---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/test-unit.sh

params:
  RUBY_VERSION: 3.2.0
  DB:           replace-me
  DB_VERSION:   replace-me
  COVERAGE:     true
