---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src
- name: bosh-cli

run:
  path: bosh-src/ci/tasks/test-upgrade.sh

params:
  RUBY_VERSION:      replace-me
  DB:                replace-me
  LOG_LEVEL:         ERROR
