---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-publisher

inputs:
  - name: bosh-src
  - name: version
  - name: stemcells-index
outputs:
  - name: version-tag
  - name: stemcells-index
    path: stemcells-index-output

run:
  path: bosh-src/ci/pipelines/stemcells/tasks/publish.sh

params:
  AWS_ACCESS_KEY_ID:     required
  AWS_SECRET_ACCESS_KEY: required
  AWS_DEFAULT_REGION:    us-east-1
  CANDIDATE_BUCKET_NAME: required
  PUBLISHED_BUCKET_NAME: required
  COPY_KEYS:             required
  OS_NAME:               required
  OS_VERSION:            required
