---
platform: linux

image: docker:///bosh/integration

inputs:
- name: bosh-src

run:
  path: bosh-src/ci/concourse/tasks/integration-wrapper.sh
  args: ["bosh-src/ci/concourse/tasks/rake.sh", "--trace", "go", "spec:integration"]

params:
  LOG_LEVEL: WARN
