azure-storage-cli/azure-storage-cli-0.0.203-linux-amd64:
  size: 10466994
  object_id: 6ac9fb56-2b38-4439-4c39-464f19fba556
  sha: sha256:700db2b085bc52047608a1e598641cc2599f7ef8ca68512784ba54f229062b19
bosh-gcscli/bosh-gcscli-0.0.350-linux-amd64:
  size: 45467220
  object_id: 25558ac8-8568-41c3-7f1a-331a22b3fd97
  sha: sha256:72a1c821ada123acdc0b975e062ee93a8893c228e9a6b16608c57f35e8cd561d
davcli/davcli-0.0.454-linux-amd64:
  size: 10167205
  object_id: d3f8af16-6e07-4b58-402c-ab44e49212da
  sha: sha256:21bd936d16ecf06e7c1d765e57727c01d8a7dbc270a391db5e9de5608342153c
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.579-linux-amd64:
  size: 4153999
  object_id: 04ba615d-8e37-4d60-5cc9-014ebe4d9708
  sha: sha256:830712c2ee5a40708198a478f6b1a0de361219fde2d5d06c7a4579c169d8715e
