bosh-gcscli/bosh-gcscli-0.0.2-linux-amd64:
  size: 12777526
  object_id: 32a1f288-c0ba-4d44-6a18-fc699afa4778
  sha: a151d3829f53b68bd15edfd3e6a527d187591992
davcli/davcli-0.0.6-linux-amd64:
  size: 8705864
  object_id: fbe6b42b-cd0e-47a6-a0b4-501be4b52426
  sha: 6b42b9833ad8f4945ce2d7f995f4dbb0e3503b08
mysql/mariadb-connector-c-2.2.1-src.tar.gz:
  size: 519628
  object_id: b7f2ab15-c9c3-4441-bb7b-f41dbf43f668
  sha: 74dd87a9537f98fc93cace2252424ae1c6c46fbf
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  size: 34179263
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fb68b2898dd0
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
mysql/server-5.7.10-3-Linux.x86_64.ssl100.tar.gz:
  size: 4639216
  object_id: 4d2023eb-9e8e-415d-9247-fc5481270eb1
  sha: f00c86bfa13b64e54f2a08551c3fe61d8966fd6e
nats/vendor/cache/daemons-1.1.9.gem:
  size: 32768
  object_id: 688133be-f542-4a6a-b139-cd1290cedcd7
  sha: e73ba58fe9e948f7edc5017f91f53b8f0a955a37
nats/vendor/cache/eventmachine-1.0.4.gem:
  size: 227840
  object_id: b6a8625f-3e04-41d1-ae69-57841921e254
  sha: 10fffa2d326e5fedc6aeaf65d2bd01d3c5e6f3ab
nats/vendor/cache/json_pure-1.8.1.gem:
  size: 148992
  object_id: ce934969-81b7-4d2b-a50c-48a9ee54d50b
  sha: 7b8f08852f734ef287468fe1676c1c4e7a9f678a
nats/vendor/cache/nats-0.5.0.beta.12.gem:
  size: 30208
  object_id: 714da93b-b55f-4adf-a5e5-b11ea991cd1f
  sha: f39b79844741d0019cd6e277ded2b2025b69bca3
nats/vendor/cache/rack-1.5.4.gem:
  size: 216064
  object_id: 61e5a9ed-2a1a-41d4-5fa8-6ec6a966ff61
  sha: d71ea9c90d7ef2a0787722f233da8fcbfb5e55d5
nats/vendor/cache/thin-1.5.1.gem:
  size: 55296
  object_id: 5b19908f-9a4c-4b03-a377-29d7b9d00a9b
  sha: 4280f5a3db7c4d6470c15f6acec9a0dded057ab8
nats/vendor/cache/yajl-ruby-1.1.0.gem:
  size: 559616
  object_id: 9d949fd3-d8d9-45f0-92ab-4a8f5a9abc56
  sha: b22512fc1bd68f495f4538d3e29735da494bea04
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.12.2.tar.gz:
  size: 981687
  object_id: 5bf3b3af-e100-497a-4a56-7a0d14603d43
  sha: 6b41d63befa4f52b0724b533e6292a6671b71fdc
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: 118f94b0-2738-4019-9aa2-1832b948a5b1
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.41.tar.gz:
  size: 2068775
  object_id: f942d349-aac1-4c78-77fc-33a38804fa83
  sha: dddf0995aefe04cc6267c1448ffef0e7b0560ec0
postgres/postgresql-9.0.23.tar.gz:
  size: 19776342
  object_id: 705f775e-0c3c-4704-8220-c5acd76dc8b8
  sha: bd793e6191a187f680566de00fa5ac8a149fb7e0
postgres/postgresql-9.4.15.tar.gz:
  size: 23509816
  object_id: 0b786dbd-8e12-40e5-49fc-86c285c51960
  sha: 3917ce873cb2e86126748dd34c848ef6092bab84
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
ruby/ruby-2.3.7.tar.gz:
  size: 17859100
  object_id: d58807cc-4f23-4108-6136-2b01b4af04a9
  sha: 540996fec64984ab6099e34d2f5820b14904f15a
ruby/rubygems-2.7.6.tgz:
  size: 852486
  object_id: c56063f1-f10e-481a-53a6-2bb5d162d340
  sha: 72a14791b96cc05a79d2a649fe7170fd1faf3e0a
ruby/yaml-0.1.7.tar.gz:
  size: 527518
  object_id: 638fbb05-dabe-4ae1-4f1a-7ae43721d77d
  sha: 3590cbf092ef4c71bc0a9b404c00a626b1e04dee
s3cli/s3cli-0.0.55-linux-amd64:
  size: 10330042
  object_id: 7131652f-fdc7-4a84-4437-c22c908e0148
  sha: 2b345d8476970bc9668af6d602e1c3fa65cff89a
verify-multidigest/verify-multidigest-0.0.29-linux-amd64:
  size: 3277550
  object_id: e5925f0e-d420-4759-4c4e-9b964183efc1
  sha: 85ce851c90a5b13aa6482c3197025c77464ce971
