bosh-gcscli/bosh-gcscli-0.0.89-linux-amd64:
  size: 19847307
  object_id: 9ed94cb7-8d75-45f6-4a58-38bbb12a1da4
  sha: sha256:03c377e04d598dd30d874d07d6773e83f603c04b9614aa2477a04233c557d7b4
davcli/davcli-0.0.126-linux-amd64:
  size: 8187372
  object_id: 715b07a1-056f-49e8-6163-34aa01fc1422
  sha: sha256:7515855f195d836649a5b9bfbbc3d9dfa65627ca9b230cacda1d0bbf7755de0d
mysql/mariadb-connector-c-3.3.3-src.tar.gz:
  size: 1387219
  object_id: 3872d7b0-6618-4cb3-6b0d-4aedb6f354cb
  sha: sha256:d77630e2376fe08185b5354621c877b0a203a6b186a0694574d37b764aeb2874
nats/nats-server-v2.9.11-linux-amd64.tar.gz:
  size: 4921062
  object_id: bc2e2d90-29f2-4010-6ea1-3cbd0e9eff66
  sha: sha256:7491944084cd0128c1ddf9a313095817a2c558b0911581c98e65b84779110856
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.9.tar.gz:
  size: 28087413
  object_id: 8b307af4-90b0-426b-47eb-e5a0430294d6
  sha: sha256:edac4c7df35e62331dd7067665d4149536be092a313bb1fe950780967a9e57dd
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.169-linux-amd64:
  size: 12505749
  object_id: 5f68473f-1225-4c3c-485b-c0aa59d94ad1
  sha: sha256:027098382cfe717936739aaa0be8b69c5e406decec94ce6e4fc63c9e90d18aca
verify-multidigest/verify-multidigest-0.0.348-linux-amd64:
  size: 3342207
  object_id: c34b58db-00ff-4190-75bc-543b1a3c6e99
  sha: sha256:70e4c36fdaffc76ff9d0cef505cadde677112c097e73a574a61aa12a17302473
