azure-storage-cli/azure-storage-cli-0.0.193-linux-amd64:
  size: 10460814
  object_id: 865793c0-cdc6-4493-7796-a586e8475555
  sha: sha256:eba87dd5bc5687baeeff2b1952d37e996d02b45096728119e5d95a8a33992712
bosh-gcscli/bosh-gcscli-0.0.340-linux-amd64:
  size: 45320951
  object_id: d34815c4-ead8-44d1-651e-b87fdfab9a65
  sha: sha256:91c28ddb4677f9cbd519a91fbba6445c093c10d47ffadecb8fa41a785be4c813
davcli/davcli-0.0.441-linux-amd64:
  size: 10160720
  object_id: 79a03827-cbd9-4814-5edb-0ee4acb2281e
  sha: sha256:a9f3849d18892ec407c99bbaa9cf67aa844b256fc114e7d7a45ed6bde98f223b
mysql/mariadb-connector-c-3.4.7-src.tar.gz:
  size: 1378870
  object_id: 60b3370f-5684-4eeb-5eec-f4ce234fd800
  sha: sha256:33bb61168380af706b9e9531396cca223179ac2f9fe72edeae69e4546d7b7a2b
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.22.tar.gz:
  size: 28473799
  object_id: 1cc12d17-0d7b-45ea-79d7-c2fb63d89695
  sha: sha256:a096c3b298adacd687991f4d4cf6e0d6dceb97ec031b6c23b3eec9080caa854c
postgres/postgresql-15.14.tar.gz:
  size: 30560938
  object_id: 679a877e-c47d-4631-6e85-b2e4a92790be
  sha: sha256:3bb652690e4a5057a4946b40f494f2f7816a5f83fc34fc7395845c326ded62d2
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.567-linux-amd64:
  size: 4151055
  object_id: 1c366954-7e22-4c07-4ce0-7a9a855f9c5e
  sha: sha256:442a6f55813f944c474dcd17e5eb69385e167603a58e694d3a7f3c2612464bf0
