bosh-gcscli/bosh-gcscli-0.0.3-linux-amd64:
  size: 12777526
  object_id: e561b18d-0d52-4579-7bd5-9823bdbe7aba
  sha: a6ca3153856b40c1af6d79da8f11efdde0899b7d
davcli/davcli-0.0.24-linux-amd64:
  size: 6165337
  object_id: aa46e12b-6aa9-4de7-5694-955799bea8ad
  sha: de7307b184f03caff746ae2ad78bf94ba04c9c71
gnatsd/gnatsd-0.9.6-bosh.12-linux-amd64:
  size: 9505349
  object_id: 54d32ad0-9d4a-4b5d-7431-7f504bd9fb9a
  sha: a801c9fa84f29f9885d54739a3c284c7f58d56bb
mysql/mariadb-connector-c-2.2.1-src.tar.gz:
  size: 519628
  object_id: b7f2ab15-c9c3-4441-bb7b-f41dbf43f668
  sha: 74dd87a9537f98fc93cace2252424ae1c6c46fbf
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  size: 34179263
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fb68b2898dd0
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
mysql/server-5.7.10-3-Linux.x86_64.ssl100.tar.gz:
  size: 4639216
  object_id: 4d2023eb-9e8e-415d-9247-fc5481270eb1
  sha: f00c86bfa13b64e54f2a08551c3fe61d8966fd6e
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.12.1.tar.gz:
  size: 981093
  object_id: 740ca33e-2b75-4b22-5713-e5791471ec49
  sha: 71000022267589f50e83b0d6743923c1b7e64238
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: 118f94b0-2738-4019-9aa2-1832b948a5b1
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.40.tar.gz:
  size: 2065161
  object_id: 55ecdf7e-38b1-4fd8-68e8-e28285ec19eb
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
postgres/postgresql-9.0.23.tar.gz:
  size: 19776342
  object_id: 705f775e-0c3c-4704-8220-c5acd76dc8b8
  sha: bd793e6191a187f680566de00fa5ac8a149fb7e0
postgres/postgresql-9.4.12.tar.gz:
  size: 23420452
  object_id: 50a5bc6e-454a-4cb3-62de-78482ca4b03d
  sha: 1405b6faf980c6a6ddd6869856a9859f6e13bcae
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.64-linux-amd64:
  size: 10341472
  object_id: 90012a1c-100d-4d73-56e8-039b88d8ea72
  sha: 73278ee6dca087f675026a8e4ecbac66b8982b99
verify-multidigest/verify-multidigest-0.0.29-linux-amd64:
  size: 3277550
  object_id: e5925f0e-d420-4759-4c4e-9b964183efc1
  sha: 85ce851c90a5b13aa6482c3197025c77464ce971
