azure-storage-cli/azure-storage-cli-0.0.216-linux-amd64:
  size: 10663107
  object_id: e300ded3-99fe-4e03-5c30-ef00ed2e5871
  sha: sha256:0e6ea953cd00e63a2d55396e7d61caa0700f1a6689709b806a5f3e7d6e03a811
bosh-gcscli/bosh-gcscli-0.0.362-linux-amd64:
  size: 46325630
  object_id: aebf32de-18e1-4171-7127-599680b841c1
  sha: sha256:739b1b5c691b5581e64e3925fed836fe0a5a3491806c4ab0b30d42fc880bf467
davcli/davcli-0.0.459-linux-amd64:
  size: 10425056
  object_id: 4a128f3d-f21e-4de2-792d-ed50d0173eee
  sha: sha256:ea14c5d74e896fea23693d9cf13e3a32c6571afb70d04d230d168bf9997d1993
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.12.4-linux-amd64.tar.gz:
  size: 6586735
  object_id: ca86df15-4e23-4aca-5a6b-e68d81296f47
  sha: sha256:92388f2e4aa1e6dea402eb173cbdb1fcb1df9a9c899cb807b91ddbb45c131b65
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.16.tar.gz:
  size: 30671899
  object_id: 978e7877-8a6f-490d-6dc4-93afc379ab41
  sha: sha256:2de4ea28ee9629d7ced8a0ee264fb6a2f817b082c52aaa281eeef6d95ba73d58
s3cli/s3cli-0.0.390-linux-amd64:
  size: 16176560
  object_id: 7de8fb87-d4c1-4121-60bf-ac1d3a4999fb
  sha: sha256:0279f728071e8b22509dbab795bfca5c282e4f4cf94a51689aefd0052d7b6bc3
verify-multidigest/verify-multidigest-0.0.592-linux-amd64:
  size: 4304107
  object_id: 88159435-3317-4db7-657b-71316b700503
  sha: sha256:a771c0492dc9e7acbc58afab67fd7405872a92df0cb0103020bd2fed4d929ac6
