bosh-gcscli/bosh-gcscli-0.0.93-linux-amd64:
  size: 19859792
  object_id: a4b41332-5a60-48ba-496b-3ff194f4dee3
  sha: sha256:d718f63800273d29718b4a5139bbe19e0cc360ad2aa4eed4543ced92c13aefb1
davcli/davcli-0.0.133-linux-amd64:
  size: 8187372
  object_id: 4beca181-1938-4204-6c85-455cef9c1d87
  sha: sha256:ed344593b22bc201f238b810204fda991c6470d4a216a0b7abdd5fae9ca62978
mysql/mariadb-connector-c-3.3.3-src.tar.gz:
  size: 1387219
  object_id: 3872d7b0-6618-4cb3-6b0d-4aedb6f354cb
  sha: sha256:d77630e2376fe08185b5354621c877b0a203a6b186a0694574d37b764aeb2874
nats/nats-server-v2.9.11-linux-amd64.tar.gz:
  size: 4921062
  object_id: bc2e2d90-29f2-4010-6ea1-3cbd0e9eff66
  sha: sha256:7491944084cd0128c1ddf9a313095817a2c558b0911581c98e65b84779110856
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.9.tar.gz:
  size: 28087413
  object_id: 8b307af4-90b0-426b-47eb-e5a0430294d6
  sha: sha256:edac4c7df35e62331dd7067665d4149536be092a313bb1fe950780967a9e57dd
postgres/postgresql-15.1.tar.gz:
  size: 29778341
  object_id: d98a42d0-afcd-4336-7786-603f5c8b6a8d
  sha: sha256:ea2cf059a85882654b989acd07edc121833164a30340faee0d3615cf7058e66c
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.171-linux-amd64:
  size: 12509941
  object_id: f48031c0-793f-4e22-646d-94f804e284a4
  sha: sha256:8ea45006531d834dbc75f0367fb2f9123c62ba3c8ca942b57a14c2595be22066
verify-multidigest/verify-multidigest-0.0.350-linux-amd64:
  size: 3342239
  object_id: 4da0b3e2-2f03-4bf0-5312-93393b278e47
  sha: sha256:d593bb1d53de89b711da0191bd4cdc2d4b32ec5a14ce917935d6e1f5985c763e
