azure-storage-cli/azure-storage-cli-0.0.216-linux-amd64:
  size: 10663107
  object_id: e300ded3-99fe-4e03-5c30-ef00ed2e5871
  sha: sha256:0e6ea953cd00e63a2d55396e7d61caa0700f1a6689709b806a5f3e7d6e03a811
bosh-gcscli/bosh-gcscli-0.0.364-linux-amd64:
  size: 46462969
  object_id: 981e0082-f1fb-4212-4064-b3b5db0132db
  sha: sha256:d3cefc17d128e37a45970525f38844ad16a4cf0251eb5f47d80d505ccc6d2ed1
davcli/davcli-0.0.459-linux-amd64:
  size: 10425056
  object_id: 4a128f3d-f21e-4de2-792d-ed50d0173eee
  sha: sha256:ea14c5d74e896fea23693d9cf13e3a32c6571afb70d04d230d168bf9997d1993
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.12.4-linux-amd64.tar.gz:
  size: 6586735
  object_id: ca86df15-4e23-4aca-5a6b-e68d81296f47
  sha: sha256:92388f2e4aa1e6dea402eb173cbdb1fcb1df9a9c899cb807b91ddbb45c131b65
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.17.tar.gz:
  size: 30677569
  object_id: adf29718-e438-4621-56c9-11cd357973c0
  sha: sha256:f7fc926ea77ffc52e9d6fd58276427e3fe14d35fd9ff3ccf724ca88a28bcb4df
s3cli/s3cli-0.0.393-linux-amd64:
  size: 16180976
  object_id: cddf84c6-b47b-45e9-7152-47e15edf286b
  sha: sha256:89dc70b4d1573dd1a743f73428d42cf2936b73faf56b7f2718989c809ebc9c25
verify-multidigest/verify-multidigest-0.0.593-linux-amd64:
  size: 4304107
  object_id: 140e1c5f-7aa6-4948-53b9-fed8c7f99298
  sha: sha256:bb6314199a95774ae0683500e5bf07fcf845af09baa7c966d9590005841b15de
