azure-storage-cli/azure-storage-cli-0.0.215-linux-amd64:
  size: 10657967
  object_id: 517d42ae-83c4-4f00-63a3-effb94afbadc
  sha: sha256:1f6a3af136a11e48f53547412ce8a691002c8fd8d3128bd84bba59a0f128b218
bosh-gcscli/bosh-gcscli-0.0.361-linux-amd64:
  size: 46202141
  object_id: 96c9311f-8f36-464b-4e59-07e2d0e41424
  sha: sha256:38dd99d6e9a49850ff12a28946806638e411a7e414c6840e6465d385ec30ce76
davcli/davcli-0.0.459-linux-amd64:
  size: 10425056
  object_id: 4a128f3d-f21e-4de2-792d-ed50d0173eee
  sha: sha256:ea14c5d74e896fea23693d9cf13e3a32c6571afb70d04d230d168bf9997d1993
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.12.4-linux-amd64.tar.gz:
  size: 6586735
  object_id: ca86df15-4e23-4aca-5a6b-e68d81296f47
  sha: sha256:92388f2e4aa1e6dea402eb173cbdb1fcb1df9a9c899cb807b91ddbb45c131b65
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.16.tar.gz:
  size: 30671899
  object_id: 978e7877-8a6f-490d-6dc4-93afc379ab41
  sha: sha256:2de4ea28ee9629d7ced8a0ee264fb6a2f817b082c52aaa281eeef6d95ba73d58
s3cli/s3cli-0.0.389-linux-amd64:
  size: 16176472
  object_id: 5a6573ef-cbe5-4b4a-65d9-1bc63ebdd3f9
  sha: sha256:b5b38923882800d5028728794c770172e37fab147113ce44c398338d35ee16d3
verify-multidigest/verify-multidigest-0.0.591-linux-amd64:
  size: 4304115
  object_id: a5f39ff2-3ada-4324-5c3a-5d1c531072a3
  sha: sha256:a69c6225080cbaad8b531d503d5296f74ad1fbc38b6790156460389b85132fa9
