bosh-gcscli/bosh-gcscli-0.0.3-linux-amd64:
  size: 12777526
  object_id: e561b18d-0d52-4579-7bd5-9823bdbe7aba
  sha: a6ca3153856b40c1af6d79da8f11efdde0899b7d
davcli/davcli-0.0.26-linux-amd64:
  size: 6179207
  object_id: 2095711c-8498-4100-42c1-e12eec8d6070
  sha: cd75e886b4f5d27ce41841d5cc902fe64bab7b78
gnatsd/gnatsd-0.9.6-bosh.13-linux-amd64:
  size: 9513901
  object_id: 6f71e068-e47d-4840-463c-47d313e1a5bd
  sha: 7d720bbf685c508c0fd566769253f91b0c7269e9
mysql/mariadb-connector-c-3.0.3-src.tar.gz:
  size: 666928
  object_id: 0d20e9e3-1a7d-4872-6ea3-28246c579ca8
  sha: 62893066d6fcd2d63075ca04a2a389b3ea6009fc
mysql/server-5.7.10-3-Linux.x86_64.ssl100.tar.gz:
  size: 4639216
  object_id: 4d2023eb-9e8e-415d-9247-fc5481270eb1
  sha: f00c86bfa13b64e54f2a08551c3fe61d8966fd6e
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.14.0.tar.gz:
  size: 1016272
  object_id: 7f2bc134-99d3-43fa-62f1-7c20955d7110
  sha: 016ab1a12c9a0c9444f9073e4300223ffd6fadbe
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: 118f94b0-2738-4019-9aa2-1832b948a5b1
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.42.tar.gz:
  size: 2081413
  object_id: 3dbd4a85-2982-425c-4ba7-eaa6a3aaba97
  sha: ee505270446f4c4bf52ac1a371335fdbb14465cb
postgres/postgresql-9.4.19.tar.gz:
  size: 23423050
  object_id: c717e25f-9d2d-4655-4b93-304d792e0a63
  sha: 36b61fd76e6de87f7c4b9b7e63daa6bba2dda1ae
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.78-linux-amd64:
  size: 12816270
  object_id: 1045caf3-776d-4ce8-646d-45a8ed176089
  sha: a3542cc6683d97a008224c5f8074e272d9d1c3ae
verify-multidigest/verify-multidigest-0.0.29-linux-amd64:
  size: 3277550
  object_id: e5925f0e-d420-4759-4c4e-9b964183efc1
  sha: 85ce851c90a5b13aa6482c3197025c77464ce971
