azure-storage-cli/azure-storage-cli-0.0.212-linux-amd64:
  size: 10457059
  object_id: fa3b5c96-6f1a-4499-4166-56462876e158
  sha: sha256:dab4fb999637b125f67a21872c7441f7f383ac2fa6c5ddfffc21a72544df2ca9
bosh-gcscli/bosh-gcscli-0.0.360-linux-amd64:
  size: 45540990
  object_id: f7abc156-1c30-422b-4054-396758fa2f1d
  sha: sha256:5a30f5469ed12ceb1e0937ad47537d21bfcdea1b260569e9b7c343c4aa3664a9
davcli/davcli-0.0.456-linux-amd64:
  size: 10167205
  object_id: c7f36839-d211-4f31-43a6-6fa2e9f19bc6
  sha: sha256:9ff26f9f134bea3c861a08f22999c46929639fb3e3497bccbb0bbe9bb1b808ff
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.386-linux-amd64:
  size: 15604986
  object_id: 7e646842-1ce3-434f-5dcf-13ff7512d5e1
  sha: sha256:c91fd206c6416ca90488ddb6f3e779e56fe73eafc3d00d73a64340d718aeda82
verify-multidigest/verify-multidigest-0.0.590-linux-amd64:
  size: 4304107
  object_id: 2edb9c85-037e-433c-52af-fd3bb44a1a62
  sha: sha256:915aa3edfb2bbc980e1183a2f07039f2b455fee7f07d522671d900ec515962f3
