bosh-gcscli/bosh-gcscli-0.0.2-linux-amd64:
  size: 12777526
  object_id: 32a1f288-c0ba-4d44-6a18-fc699afa4778
  sha: a151d3829f53b68bd15edfd3e6a527d187591992
davcli/davcli-0.0.6-linux-amd64:
  size: 8705864
  object_id: fbe6b42b-cd0e-47a6-a0b4-501be4b52426
  sha: 6b42b9833ad8f4945ce2d7f995f4dbb0e3503b08
gnatsd/gnatsd-0.9.6+2017-09-11T16_05_36Z-4ae1ca3-linux-amd64:
  size: 9505349
  object_id: bf280241-e422-4d35-7608-6a6700cf31c2
  sha: e2c22a94cf9abc84261a515d069817274deee3e2
golang/go1.7.5.linux-amd64.tar.gz:
  size: 84176916
  object_id: c442e2e9-2f9f-4c8f-623f-c1c65da76a50
  sha: 7c6902ce8cd3b9963082d748c50df074e4896796
mysql/mariadb-connector-c-2.2.1-src.tar.gz:
  size: 519628
  object_id: b7f2ab15-c9c3-4441-bb7b-f41dbf43f668
  sha: 74dd87a9537f98fc93cace2252424ae1c6c46fbf
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  size: 34179263
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fb68b2898dd0
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
mysql/server-5.7.10-3-Linux.x86_64.ssl100.tar.gz:
  size: 4639216
  object_id: 4d2023eb-9e8e-415d-9247-fc5481270eb1
  sha: f00c86bfa13b64e54f2a08551c3fe61d8966fd6e
nats/vendor/cache/daemons-1.1.9.gem:
  size: 32768
  object_id: 688133be-f542-4a6a-b139-cd1290cedcd7
  sha: e73ba58fe9e948f7edc5017f91f53b8f0a955a37
nats/vendor/cache/eventmachine-1.0.4.gem:
  size: 227840
  object_id: b6a8625f-3e04-41d1-ae69-57841921e254
  sha: 10fffa2d326e5fedc6aeaf65d2bd01d3c5e6f3ab
nats/vendor/cache/json_pure-1.8.1.gem:
  size: 148992
  object_id: ce934969-81b7-4d2b-a50c-48a9ee54d50b
  sha: 7b8f08852f734ef287468fe1676c1c4e7a9f678a
nats/vendor/cache/nats-0.5.0.beta.12.gem:
  size: 30208
  object_id: 714da93b-b55f-4adf-a5e5-b11ea991cd1f
  sha: f39b79844741d0019cd6e277ded2b2025b69bca3
nats/vendor/cache/rack-1.5.4.gem:
  size: 216064
  object_id: 61e5a9ed-2a1a-41d4-5fa8-6ec6a966ff61
  sha: d71ea9c90d7ef2a0787722f233da8fcbfb5e55d5
nats/vendor/cache/thin-1.5.1.gem:
  size: 55296
  object_id: 5b19908f-9a4c-4b03-a377-29d7b9d00a9b
  sha: 4280f5a3db7c4d6470c15f6acec9a0dded057ab8
nats/vendor/cache/yajl-ruby-1.1.0.gem:
  size: 559616
  object_id: 9d949fd3-d8d9-45f0-92ab-4a8f5a9abc56
  sha: b22512fc1bd68f495f4538d3e29735da494bea04
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.12.1.tar.gz:
  size: 981093
  object_id: 740ca33e-2b75-4b22-5713-e5791471ec49
  sha: 71000022267589f50e83b0d6743923c1b7e64238
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: 118f94b0-2738-4019-9aa2-1832b948a5b1
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.40.tar.gz:
  size: 2065161
  object_id: 55ecdf7e-38b1-4fd8-68e8-e28285ec19eb
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
postgres/postgresql-9.0.23.tar.gz:
  size: 19776342
  object_id: 705f775e-0c3c-4704-8220-c5acd76dc8b8
  sha: bd793e6191a187f680566de00fa5ac8a149fb7e0
postgres/postgresql-9.4.12.tar.gz:
  size: 23420452
  object_id: 50a5bc6e-454a-4cb3-62de-78482ca4b03d
  sha: 1405b6faf980c6a6ddd6869856a9859f6e13bcae
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
ruby/bundler-1.15.3.gem:
  size: 336384
  object_id: faae3244-82c9-400b-542b-2da1741f01e7
  sha: bd1e1ba80789ea013a11a2909a154dcee118ebbc
ruby/ruby-2.3.1.tar.gz:
  size: 17797997
  object_id: bcd99e02-ae75-4d74-beff-ab517520c75c
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
ruby/rubygems-2.6.4.tgz:
  size: 478582
  object_id: 91c3d9ab-be40-4d2b-a3d0-0cdcccb48ebe
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
ruby/yaml-0.1.7.tar.gz:
  size: 527518
  object_id: 638fbb05-dabe-4ae1-4f1a-7ae43721d77d
  sha: 3590cbf092ef4c71bc0a9b404c00a626b1e04dee
s3cli/s3cli-0.0.55-linux-amd64:
  size: 10330042
  object_id: 7131652f-fdc7-4a84-4437-c22c908e0148
  sha: 2b345d8476970bc9668af6d602e1c3fa65cff89a
verify-multidigest/verify-multidigest-0.0.29-linux-amd64:
  size: 3277550
  object_id: e5925f0e-d420-4759-4c4e-9b964183efc1
  sha: 85ce851c90a5b13aa6482c3197025c77464ce971
