azure-storage-cli/azure-storage-cli-0.0.194-linux-amd64:
  size: 10460806
  object_id: 2ef5cefd-c939-4bcf-5ffb-91dc30d79b92
  sha: sha256:ebb7e2c6f7b7ccc5e041adc78171013d05cf6a9ba9e45105945ec6617d3ca13c
bosh-gcscli/bosh-gcscli-0.0.340-linux-amd64:
  size: 45320951
  object_id: d34815c4-ead8-44d1-651e-b87fdfab9a65
  sha: sha256:91c28ddb4677f9cbd519a91fbba6445c093c10d47ffadecb8fa41a785be4c813
davcli/davcli-0.0.442-linux-amd64:
  size: 10160720
  object_id: 79d0e93a-c0f9-4782-6d0a-cab1b4d534ce
  sha: sha256:36e1919b585078eb91ed31fc6a29e0001a72930f6c3e801a42f29591b02febab
mysql/mariadb-connector-c-3.4.7-src.tar.gz:
  size: 1378870
  object_id: 60b3370f-5684-4eeb-5eec-f4ce234fd800
  sha: sha256:33bb61168380af706b9e9531396cca223179ac2f9fe72edeae69e4546d7b7a2b
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.14.tar.gz:
  size: 30560938
  object_id: 679a877e-c47d-4631-6e85-b2e4a92790be
  sha: sha256:3bb652690e4a5057a4946b40f494f2f7816a5f83fc34fc7395845c326ded62d2
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.567-linux-amd64:
  size: 4151055
  object_id: 1c366954-7e22-4c07-4ce0-7a9a855f9c5e
  sha: sha256:442a6f55813f944c474dcd17e5eb69385e167603a58e694d3a7f3c2612464bf0
