azure-storage-cli/azure-storage-cli-0.0.198-linux-amd64:
  size: 10460651
  object_id: 947a2e57-ce69-41c6-6d16-bbd208f4428b
  sha: sha256:032938af98a63be620f72ba026dd4cba99b1e90e7a0816918b46e60189609956
bosh-gcscli/bosh-gcscli-0.0.342-linux-amd64:
  size: 45320975
  object_id: 6f5b3786-35de-4fcb-490d-4fc4dd115ecf
  sha: sha256:0287c7eec20f9d4db862b03ec4f80327a5d55db53e2dcb8fb4aa5dd834a54fac
davcli/davcli-0.0.443-linux-amd64:
  size: 10167565
  object_id: 5b2bb3ae-d2f1-4a23-55cc-9a599cff1d08
  sha: sha256:f280a3cfb6cb7070ba7989f2073a7eaa9744b8ccb130ea66fe022358af25b010
mysql/mariadb-connector-c-3.4.7-src.tar.gz:
  size: 1378870
  object_id: 60b3370f-5684-4eeb-5eec-f4ce234fd800
  sha: sha256:33bb61168380af706b9e9531396cca223179ac2f9fe72edeae69e4546d7b7a2b
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.569-linux-amd64:
  size: 4151055
  object_id: 013a816d-c0bf-4914-4b78-b3b4c783f806
  sha: sha256:0b82e85b30836ab92f80b02370af4ed687a9f430fd045912c12d3e1236986274
