azure-storage-cli/azure-storage-cli-0.0.195-linux-amd64:
  size: 10460806
  object_id: c57527b4-193b-4a2d-69d6-9715b4d1edd8
  sha: sha256:a9ac9dc322115eda9801f1ccf8c471d4d41ac604b69a62236138b0933071a5de
bosh-gcscli/bosh-gcscli-0.0.341-linux-amd64:
  size: 45320975
  object_id: 5faf8c39-a523-4457-5e2c-9602a9945038
  sha: sha256:8b22f21cef95b7e864bdea1a3a39d20bbed3fa698821f461d2db7827062c78c8
davcli/davcli-0.0.442-linux-amd64:
  size: 10160720
  object_id: 79d0e93a-c0f9-4782-6d0a-cab1b4d534ce
  sha: sha256:36e1919b585078eb91ed31fc6a29e0001a72930f6c3e801a42f29591b02febab
mysql/mariadb-connector-c-3.4.7-src.tar.gz:
  size: 1378870
  object_id: 60b3370f-5684-4eeb-5eec-f4ce234fd800
  sha: sha256:33bb61168380af706b9e9531396cca223179ac2f9fe72edeae69e4546d7b7a2b
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.568-linux-amd64:
  size: 4151055
  object_id: 5bb3b1cc-453c-4e19-4941-1d7460d1486c
  sha: sha256:d9ca7ebd22e7778b632b91e5587b0892105a79c047bed9e882e9ed6bc235be85
