bosh-gcscli/bosh-gcscli-0.0.18-linux-amd64:
  size: 15517961
  object_id: 0c9bed44-68b6-4101-7db9-fad5139906fb
  sha: sha256:7a657f24509b1594764194e9c90f5540d7657aec49f79bf44cb1a04ce15e68ed
davcli/davcli-0.0.41-linux-amd64:
  size: 8595966
  object_id: 76cdbca6-03f2-4a7b-6f11-90e11366fe19
  sha: sha256:2707e21d5c0805f3a606144256ed61d3cc136cb7706565a99c4fb030add302e8
gnatsd/gnatsd-1.3.0-bosh.10-linux-amd64:
  size: 11642415
  object_id: 3ee87236-4c36-4477-7bb1-840056c62dde
  sha: sha256:e5362a7c88ed92d4f4263b1b725e901fe29da220c3548e37570793776b5f6d51
mysql/mariadb-connector-c-3.0.10-src.tar.gz:
  size: 668385
  object_id: 5b52bf8e-3e51-47e8-5a60-29f07b2d241d
  sha: sha256:bd9aa1f137ead3dc68ed3165adc53541712076d08949800b6ccebd33da6d0ae8
mysql/mariadb-connector-c-3.1.11-src.tar.gz:
  size: 752342
  sha: sha256:3e6f6c399493fe90efdc21a3fe70c30434b7480e8195642a959f1dd7a0fa5b0f
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.17.10.tar.gz:
  size: 1039541
  object_id: e4269c7d-0455-44f3-7ad8-af1a06dfb542
  sha: sha256:a9aa73f19c352a6b166d78e2a664bb3ef1295bbe6d3cc5aa7404bd4664ab4b83
nginx/nginx-upload-module-2.3.0.tar.gz:
  size: 40139
  object_id: 598d93c6-90b8-4472-5308-5235bb476a45
  sha: sha256:c86e318addb9c88d70fdbd58ff1f6ef6f404a93070f6db8017a1f880c97946c4
nginx/ngx_http_hmac_secure_link_module-0.3.tar.gz:
  size: 5452
  object_id: 9901c036-d3dd-4167-4fc0-41be17deef02
  sha: sha256:0d4a69f39b513a3427f5fb41a7503844e703395ca04517d0a55400e4a3150927
nginx/pcre-8.44.tar.gz:
  size: 2090750
  object_id: e7dd6f33-c214-428f-46fb-b94ecd3ae9b7
  sha: sha256:aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728
postgres/postgresql-9.4.23.tar.gz:
  size: 21943235
  object_id: 94e77351-2ede-4657-46ae-8208e2aee252
  sha: sha256:82e29128463bfb1961c4119d9da893baaa437620a29bc53ce08bf735b5810ea4
postgres/postgresql-10.12.tar.gz:
  size: 24940708
  object_id: f9146302-0391-459c-6f19-5d3958a3a43d
  sha: sha256:a1a32c2b91bc5e3cb46b56f44d6b6baf82cd27eff973d6c1785f4ab93e34d23b
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.95-linux-amd64:
  size: 15481029
  object_id: 1ea1d53d-8ff1-4075-5760-2bdce086974d
  sha: sha256:4f280cadec594f8767d7d1398e76c06dadc0f566b5b17ec8f08062629f471221
verify-multidigest/verify-multidigest-0.0.156-linux-amd64:
  size: 4321727
  object_id: b690a1d1-eda4-484a-5ef4-19c478e0ccb4
  sha: sha256:f72a33761540d010c136d020038e764d04ddc9a1ee71ffd2367304f18ba550d3
