bosh-gcscli/bosh-gcscli-0.0.94-linux-amd64:
  size: 19859642
  object_id: 4c88f637-4c7a-4663-70a5-e0c6acde2892
  sha: sha256:447a81e8fe137aa9a429a78e5ec5477f9dd2677f1035f497c515aed1700dc700
davcli/davcli-0.0.138-linux-amd64:
  size: 8187372
  object_id: 46ac5a91-0f36-47ca-7353-1622dcbb6774
  sha: sha256:6ca4540574acb3109a30a8409d71c08e7113680cff8f47d3ecab03bbe2b3713b
mysql/mariadb-connector-c-3.3.3-src.tar.gz:
  size: 1387219
  object_id: 3872d7b0-6618-4cb3-6b0d-4aedb6f354cb
  sha: sha256:d77630e2376fe08185b5354621c877b0a203a6b186a0694574d37b764aeb2874
nats/nats-server-v2.9.11-linux-amd64.tar.gz:
  size: 4921062
  object_id: bc2e2d90-29f2-4010-6ea1-3cbd0e9eff66
  sha: sha256:7491944084cd0128c1ddf9a313095817a2c558b0911581c98e65b84779110856
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.9.tar.gz:
  size: 28087413
  object_id: 8b307af4-90b0-426b-47eb-e5a0430294d6
  sha: sha256:edac4c7df35e62331dd7067665d4149536be092a313bb1fe950780967a9e57dd
postgres/postgresql-15.1.tar.gz:
  size: 29778341
  object_id: d98a42d0-afcd-4336-7786-603f5c8b6a8d
  sha: sha256:ea2cf059a85882654b989acd07edc121833164a30340faee0d3615cf7058e66c
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.174-linux-amd64:
  size: 12509941
  object_id: 91e4fda9-117c-4d46-6232-6997c4cac65b
  sha: sha256:75ce7c1392cd1ce7b6089f83e773e3b06057621c01c51073b98d0aa40106e60e
verify-multidigest/verify-multidigest-0.0.350-linux-amd64:
  size: 3342239
  object_id: 4da0b3e2-2f03-4bf0-5312-93393b278e47
  sha: sha256:d593bb1d53de89b711da0191bd4cdc2d4b32ec5a14ce917935d6e1f5985c763e
