azure-storage-cli/azure-storage-cli-0.0.146-linux-amd64:
  size: 10183017
  object_id: 301ed697-bcc4-4cb4-77ad-e229ebe02ca3
  sha: sha256:027a5bcf0f5a679f617bdd178fff99e846c139ab3c4eb0eb320e91ddc4bf83f9
bosh-gcscli/bosh-gcscli-0.0.280-linux-amd64:
  size: 44722199
  object_id: 2f5ccf40-e1be-46a9-6179-ab4ab2846cbd
  sha: sha256:8a8aeb6fd4f6583718ac7af45e4426e4e9573a9147b03bcf76137a5d7c77806a
davcli/davcli-0.0.399-linux-amd64:
  size: 10123001
  object_id: 2f46b045-119b-4f5e-7c44-b1e66f268b69
  sha: sha256:52e21e9cedba91669c1979c13195efe13c419df3a27b6abf0e900637bcf73405
mysql/mariadb-connector-c-3.4.4-src.tar.gz:
  size: 1431570
  object_id: 14dba3dc-db2e-4b1d-75ed-f064a06f22f8
  sha: sha256:58876fad1c2d33979d78bbfa61d7a3476e8faa2cd0af0f7f8bfeb06deaa1034e
nats/nats-server-v2.10.25-linux-amd64.tar.gz:
  size: 5901276
  object_id: 450ffcec-f0bd-4140-4e87-9806c6659bea
  sha: sha256:8a54ebad5f08311257e4267a96c5333ae58667c3ef50a7897bce00e01f6d8d6c
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.19.tar.gz:
  size: 28405411
  object_id: 22de1cd6-ee97-4d0c-6619-f95e55b92317
  sha: sha256:480745a8d0a6e20cb4100c2ba72d41339b1ccdd42aa801e423c3221e33663181
postgres/postgresql-15.11.tar.gz:
  size: 30473181
  object_id: a428d8a5-1231-4696-4d63-7188e9e26dd7
  sha: sha256:177cec755c710b3f1305a1e0fa0d89622ad0a31b49966d929515d845ab2e4a3e
s3cli/s3cli-0.0.352-linux-amd64:
  size: 17235111
  object_id: 7b4918e8-e818-46c2-601f-861be91c7a97
  sha: sha256:eff937ae7e2ccaab5b325dc5ec12c6df82d08e356e6d65bf5ba288be6f788b2a
verify-multidigest/verify-multidigest-0.0.531-linux-amd64:
  size: 4174759
  object_id: 263e377d-0f1e-4892-4dde-a337e4fe5cdc
  sha: sha256:a2a9741a7f3490ce3d612285e8cde8cd3686ccd018a7dc90c8edf4b10d5cdee5
