bosh-gcscli/bosh-gcscli-0.0.103-linux-amd64:
  size: 19905959
  object_id: 25233714-567d-4ba5-477c-ca0a1582fe45
  sha: sha256:444e1ce32c08aeec862df3dd3813a71ea584c0709977eaaa407a6fe784a3783b
davcli/davcli-0.0.154-linux-amd64:
  size: 8298762
  object_id: 24e8fa6b-df1b-4728-5086-e1882a4ab1a2
  sha: sha256:c990b9f53cd93a591b888b048e9703ddeda41bef61d85bff177e8eaa8a7536e1
mysql/mariadb-connector-c-3.3.4-src.tar.gz:
  size: 1389030
  object_id: e6765d6b-8abc-453d-65d8-dea24fccf0de
  sha: sha256:486e5fdf976a8e7fadf583ae912128655e013ac575fa79b2d1af0fb8827a78ed
nats/nats-server-v2.9.14-linux-amd64.tar.gz:
  size: 4929150
  object_id: 8f4c7785-6071-4982-6414-4d21846138a9
  sha: sha256:18ac6d0a3956a3d293b85c33822159188b9e75b7597241e2c821e9ded7456601
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.10.tar.gz:
  size: 28117237
  object_id: 2456aabe-21c8-4049-6b6a-428190795d3a
  sha: sha256:a0a6b1b2e575fb15aa617fb77d3f2558ffd58a456e58d7d147539923d46d79cc
postgres/postgresql-15.2.tar.gz:
  size: 29811750
  object_id: fab6d841-010e-4278-55f9-6351d4654a77
  sha: sha256:eccd208f3e7412ad7bc4c648ecc87e0aa514e02c24a48f71bf9e46910bf284ca
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.177-linux-amd64:
  size: 12613913
  object_id: 6bdbabbe-5ffd-4797-4695-34d60d5b6ce3
  sha: sha256:816e0bbcf77e7e0aec4135ebe01e58aebd084e8d7bfcf85cbde8f9c680098d6a
verify-multidigest/verify-multidigest-0.0.354-linux-amd64:
  size: 3109852
  object_id: 69955faa-6777-405e-6f83-83c8dcaeedd0
  sha: sha256:67f25296ea8472f33eaa272972ba7a4b0cc84b6258b00016581fb46c61dc6fe5
