bosh-gcscli/bosh-gcscli-0.0.18-linux-amd64:
  size: 15517961
  object_id: 0c9bed44-68b6-4101-7db9-fad5139906fb
  sha: sha256:7a657f24509b1594764194e9c90f5540d7657aec49f79bf44cb1a04ce15e68ed
davcli/davcli-0.0.41-linux-amd64:
  size: 8595966
  object_id: 76cdbca6-03f2-4a7b-6f11-90e11366fe19
  sha: sha256:2707e21d5c0805f3a606144256ed61d3cc136cb7706565a99c4fb030add302e8
gnatsd/gnatsd-1.3.0-bosh.10-linux-amd64:
  size: 11642415
  object_id: 3ee87236-4c36-4477-7bb1-840056c62dde
  sha: sha256:e5362a7c88ed92d4f4263b1b725e901fe29da220c3548e37570793776b5f6d51
mysql/mariadb-connector-c-3.1.13-src.tar.gz:
  size: 968401
  object_id: b3c4867c-ca9f-4819-4e11-e62595e7bd77
  sha: sha256:0271a5edfd64b13bca5937267474e4747d832ec62e169fc2589d2ead63746875
postgres/postgresql-9.4.23.tar.gz:
  size: 21943235
  object_id: 94e77351-2ede-4657-46ae-8208e2aee252
  sha: sha256:82e29128463bfb1961c4119d9da893baaa437620a29bc53ce08bf735b5810ea4
postgres/postgresql-10.22.tar.gz:
  size: 25460734
  object_id: 108d738e-cd36-4e1d-4aa8-4bb6a9386fa7
  sha: sha256:3ca98f49a31f595fd90664818eaa35a7a96d86123aedda8a023b2be8c96733f2
postgres/postgresql-13.2.tar.gz:
  size: 27548921
  object_id: dcbe8474-8120-49b9-7fce-ca483daabaf8
  sha: sha256:3386a40736332aceb055c7c9012ecc665188536d874d967fcc5a33e7992f8080
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.95-linux-amd64:
  size: 15481029
  object_id: 1ea1d53d-8ff1-4075-5760-2bdce086974d
  sha: sha256:4f280cadec594f8767d7d1398e76c06dadc0f566b5b17ec8f08062629f471221
verify-multidigest/verify-multidigest-0.0.156-linux-amd64:
  size: 4321727
  object_id: b690a1d1-eda4-484a-5ef4-19c478e0ccb4
  sha: sha256:f72a33761540d010c136d020038e764d04ddc9a1ee71ffd2367304f18ba550d3
