bosh-gcscli/bosh-gcscli-0.0.3-linux-amd64:
  size: 12777526
  object_id: e561b18d-0d52-4579-7bd5-9823bdbe7aba
  sha: a6ca3153856b40c1af6d79da8f11efdde0899b7d
davcli/davcli-0.0.33-linux-amd64:
  size: 7650033
  object_id: 332c86ac-1f03-47a1-6b70-27b981c80734
  sha: sha256:16869bcdced5bb8221293ded97b9294f2639c5442b1b4ceb844c4e04d6a1f98b
gnatsd/gnatsd-1.3.0-bosh.2-linux-amd64:
  size: 10471093
  object_id: cbc9d252-ca0c-4120-6f36-1a6e856b1f03
  sha: add5c727ae5853d41f5eb1d880bfbb26245588aa
mysql/mariadb-connector-c-3.0.3-src.tar.gz:
  size: 666928
  object_id: 0d20e9e3-1a7d-4872-6ea3-28246c579ca8
  sha: 62893066d6fcd2d63075ca04a2a389b3ea6009fc
mysql/server-5.7.10-3-Linux.x86_64.ssl100.tar.gz:
  size: 4639216
  object_id: 4d2023eb-9e8e-415d-9247-fc5481270eb1
  sha: f00c86bfa13b64e54f2a08551c3fe61d8966fd6e
nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: ee5b4828-67f9-42f7-a0fb-23b4d4c9805f
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.14.2.tar.gz:
  size: 1015384
  object_id: 2f92c66b-3d1b-46e7-7433-21c31ce9f328
  sha: sha256:002d9f6154e331886a2dd4e6065863c9c1cf8291ae97a1255308572c02be9797
nginx/nginx-upload-module-2.3.0.tar.gz:
  size: 40139
  object_id: 598d93c6-90b8-4472-5308-5235bb476a45
  sha: sha256:c86e318addb9c88d70fdbd58ff1f6ef6f404a93070f6db8017a1f880c97946c4
nginx/pcre-8.43.tar.gz:
  size: 2085854
  object_id: 09de2178-6d0a-44ff-77bd-931848e6ee89
  sha: sha256:0b8e7465dc5e98c757cc3650a20a7843ee4c3edf50aaf60bb33fd879690d2c73
postgres/postgresql-9.4.19.tar.gz:
  size: 23423050
  object_id: c717e25f-9d2d-4655-4b93-304d792e0a63
  sha: 36b61fd76e6de87f7c4b9b7e63daa6bba2dda1ae
postgres/postgresql-10.6.tar.gz:
  size: 26902911
  object_id: f4837fff-c593-43eb-4704-56d489d3582c
  sha: 3c10c2ba99ffe72758c868f252e459926cea8452
powerdns/pdns-static_3.3.1-1_amd64.deb:
  size: 9353694
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
s3cli/s3cli-0.0.80-linux-amd64:
  size: 12102238
  object_id: 45ee9a15-fef2-4dfb-417b-934de60a795c
  sha: sha256:811dfe3f0dfc6b51d12aa3910069c6c90a15354e9823243a75c5f3762b4a9e3a
verify-multidigest/verify-multidigest-0.0.121-linux-amd64:
  size: 4077590
  object_id: 60542f17-db12-474d-66ae-36af797de24d
  sha: sha256:5429b7d760a5083467f049ae9f32582da871e6e2cebf0931aee6372f4305bc29
