azure-storage-cli/azure-storage-cli-0.0.202-linux-amd64:
  size: 10460651
  object_id: f2470e79-a938-4b6c-4577-caa82f23da22
  sha: sha256:d3ea330177ff7ccc98a6c538ff76fc173d58133e27365c45a70afabf526df526
bosh-gcscli/bosh-gcscli-0.0.349-linux-amd64:
  size: 45385369
  object_id: 6a2156fd-3615-427f-62b6-272fc8e3c26d
  sha: sha256:98aedfccb12cff0a621e8d2feedd8431d124611b22719adbd0a7f225d0f19499
davcli/davcli-0.0.448-linux-amd64:
  size: 10167205
  object_id: ec146c5c-453c-4f76-4993-79add42c138a
  sha: sha256:da829bfa89b70ca7146813a5f702a315dff17bcf81d1f19efb39883ec1811bdc
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.382-linux-amd64:
  size: 17092710
  object_id: f2dfa879-daea-42d8-76a9-c7cd70c6117b
  sha: sha256:6fdcdf596ee83c5d87f61793fa80beb9a14e180e69a1c96745591df869092264
verify-multidigest/verify-multidigest-0.0.576-linux-amd64:
  size: 4153991
  object_id: f64c2572-eea2-45d7-571b-8fb601396262
  sha: sha256:12259724a940155d3c84b6f9a90849344893bfef414ee287d052ac49396e4eda
