azure-storage-cli/azure-storage-cli-0.0.210-linux-amd64:
  size: 10457059
  object_id: 4205c430-0626-4950-415c-6ebd8a52acdc
  sha: sha256:e3dd67b6136c9604391cbefa22eed5d584fee92aedb5968cd5256cfcf65146eb
bosh-gcscli/bosh-gcscli-0.0.357-linux-amd64:
  size: 45488067
  object_id: 5e23c4a0-368e-4f7a-55b3-f89be8e87068
  sha: sha256:d0537773a4d54ad399618e3e2023bd5aa791bf21b963aa3c41bde83a77fd2be1
davcli/davcli-0.0.455-linux-amd64:
  size: 10167205
  object_id: 4172180f-7547-4cb0-5bad-57253728f6a7
  sha: sha256:fd2e29111d3ad14165fc64b9434f7d46ec5ff3a2cc2853960e300bc5954d4de0
mysql/mariadb-connector-c-3.4.8-src.tar.gz:
  size: 1380411
  object_id: 31e2e6c6-eefe-4512-68bd-757a7c27b044
  sha: sha256:156aed3b49f857d0ac74fb76f1982968bcbfd8382da3f5b6ae71f616729920d7
nats/nats-server-v2.11.2-linux-amd64.tar.gz:
  size: 6295497
  object_id: 81f2bc9a-257f-4109-4a2c-6ea0d5ef8cb7
  sha: sha256:a123c8e43abe5ca8f0bff9393547f20f4bbac6fc0fb3c586ec031855911c414a
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 1549746f-1e8d-4ce5-5585-36eca41ab528
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: c2814297-9505-46e7-7b78-9adbd0d4b8f5
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 1d489461-1064-4cbd-62e8-5de9460132ae
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
s3cli/s3cli-0.0.384-linux-amd64:
  size: 15599238
  object_id: ad504009-35ab-4417-48be-f92f34f769aa
  sha: sha256:7f1b8f195c1c453e0778413fec447de75598bed29248df15e331f92de9e0cdbd
verify-multidigest/verify-multidigest-0.0.586-linux-amd64:
  size: 4154007
  object_id: d308c2d6-c696-40ef-7669-7e777dcfe9cb
  sha: sha256:790c7b567579aec93b8352e7899e230ecf6cad0c73c6fac3504bab7a6958ad2e
