---
http:
  port: 25930

mbus:
  endpoint: nats://127.0.0.1:4222
  user:
  password:

director: &director
  endpoint: http://127.0.0.1:25555
  user:
  password:

intervals:
  poll_director: 60
  poll_grace_period: 30
  log_stats: 60
  analyze_agents: 60
  agent_timeout: 60
  rogue_agent_alert: 120
  prune_events: 30

plugins:

  - name: logger
    events:
      - alert
      - heartbeat

  - name: nats
    events:
      - alert
      - heartbeat
    options:
      endpoint: nats://127.0.0.1:4222
      user:
      password:

  - name: email
    events:
      - alert
    options:
      recipients:
        - user@example.com
      smtp:
        from: bosh.alerts@example.com
        host: smtp.example.com
        port: 25
        auth: plain
        user: user
        password: pass
        tls: true
        domain: example.com

  - name: tsdb
    events:
      - alert
      - heartbeat
    options:
      host: localhost
      port: 4242

  - name: cloud_watch
    events:
      - heartbeat
    options:
      access_key_id: access_key
      secret_access_key: secret_access_key

  - name: resurrector
    events:
      - alerts
    options:
      director: *director

  - name: data_dog
    events:
      - heartbeat
    options:
      api_key: api_key
      application_key: application_key
      pagerduty_service_name: pagerduty_service_name
