---
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca11e122004e4e8ec64843104fbd4f219f4b7
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76304fbd4f269d377
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca61e121004e4e7d51d950e04fbd4f2ca2d89
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fb68b2898dd0
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
  size: 34179263
genisoimage/cdrkit-1.1.11.tar.gz:
  object_id: bb61a16c-6078-4e18-9c1f-9c2d6f056cd6
  sha: 3f7ddc06db0272942e1a4cd98c3c96462df77387
  size: 1445133
ruby/yaml-0.1.5.tar.gz:
  object_id: db07c821-62f8-4fd1-a99a-ff1c88b2474b
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
powerdns/pdns-static_3.3.1-1_amd64.deb:
  object_id: 6e861aa6-2e83-4027-a1e8-0ebec995c274
  sha: 22bb46aa0b3e7671e0ee9aa30ed95c38841106ab
  size: 9353694
nats/vendor/cache/daemons-1.1.9.gem:
  object_id: 688133be-f542-4a6a-b139-cd1290cedcd7
  sha: e73ba58fe9e948f7edc5017f91f53b8f0a955a37
  size: 32768
nats/vendor/cache/eventmachine-1.0.3.gem:
  object_id: 530fa989-bb5d-40ff-a723-8ab058006685
  sha: f1d3c0cfcdca855b9b7efcaf9a6c907043349ac9
  size: 225792
nats/vendor/cache/json_pure-1.8.1.gem:
  object_id: ce934969-81b7-4d2b-a50c-48a9ee54d50b
  sha: 7b8f08852f734ef287468fe1676c1c4e7a9f678a
  size: 148992
nats/vendor/cache/nats-0.5.0.beta.12.gem:
  object_id: 714da93b-b55f-4adf-a5e5-b11ea991cd1f
  sha: f39b79844741d0019cd6e277ded2b2025b69bca3
  size: 30208
nats/vendor/cache/rack-1.5.2.gem:
  object_id: 8e0440d6-d7cb-4085-9b33-2957bfb9a5bd
  sha: a17f40c9beb03b458f537f42cf36dd90d8230625
  size: 216576
nats/vendor/cache/thin-1.5.1.gem:
  object_id: 5b19908f-9a4c-4b03-a377-29d7b9d00a9b
  sha: 4280f5a3db7c4d6470c15f6acec9a0dded057ab8
  size: 55296
nats/vendor/cache/yajl-ruby-1.1.0.gem:
  object_id: 9d949fd3-d8d9-45f0-92ab-4a8f5a9abc56
  sha: b22512fc1bd68f495f4538d3e29735da494bea04
  size: 559616
nginx/headers-more-v0.25.tgz:
  object_id: 62f787d7-b4e2-4530-b105-d0eade4d6728
  sha: 514bc3df30b24eb0a06533f1ebaa579b898990f5
  size: 27973
nginx/nginx-1.4.5.tar.gz:
  object_id: 3ccf2492-9a27-4de8-a179-c88bc6f95f30
  sha: 96c1aecd314f73a3c30a0db8c39ad15ddacb074e
  size: 768728
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 118f94b0-2738-4019-9aa2-1832b948a5b1
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
nginx/pcre-8.37.tar.gz:
  object_id: 7c107c29-c63b-4e95-8a13-698a835ae8b5
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
redis/redis-3.0.2.tar.gz:
  object_id: 033ba3ad-dea6-4a18-910f-e7d0f244d8ef
  sha: a38755fe9a669896f7c5d8cd3ebbf76d59712002
  size: 1360182
ruby/bundler-1.10.6.gem:
  object_id: a7313017-fac0-4306-8610-4a050339d792
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
  size: 251392
ruby/ruby-2.1.7.tar.gz:
  object_id: 3b5c759a-361b-4407-9933-4ad927fd7751
  sha: e2e195a4a58133e3ad33b955c829bb536fa3c075
  size: 15151458
ruby/rubygems-2.4.8.tgz:
  object_id: 25e5548c-2c64-4a30-9d4e-f7f7bae02578
  sha: 0db6b2f1cdd2267fe19f1f875057c2f2ce9f5696
  size: 447712
