---
nats/vendor/cache/daemons-1.1.4.gem:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae04fbd4f12c0c03
  sha: 6603f661cc3b9f591db66b5fbb18d648288651a0
  size: 33792
nats/vendor/cache/eventmachine-0.12.10.gem:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd04fbd4f140c2b7
  sha: d9b3ec65e3e94e461ed2d53c01a2b9ab62fe6a07
  size: 220672
nats/vendor/cache/json_pure-1.6.2.gem:
  object_id: rest/objects/4e4e78bca11e121204e4e86ee1529404fbd4f1585c83
  sha: d0f2fdad9414f0ec17ac4730d12a3c87134517e8
  size: 659968
nats/vendor/cache/nats-0.4.22.beta.1.gem:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407704fbd4f16ef604
  sha: a35bfbbd3b2513c7bfde53b68f750d9789c94ff4
  size: 23040
nats/vendor/cache/rack-1.3.5.gem:
  object_id: rest/objects/4e4e78bca31e122204e4e9863b1b7404fbd4f189097f
  sha: 8ceed89e9a1d0039002eca26e579de8ad5883516
  size: 155648
nats/vendor/cache/thin-1.3.1.gem:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55304fbd4f19d419b
  sha: e009f5ce3ba092299cd0810652e67c080ffaef14
  size: 141824
nats/vendor/cache/yajl-ruby-0.7.8.gem:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe59104fbd4f1b4ae88
  sha: d9a29e4321fd26dfa15cc17befccdb9442e42310
  size: 555008
nginx/headers-more-v0.15rc1.tgz:
  object_id: rest/objects/4e4e78bca41e122004e4e8ec65f67f04fbd4f1cd4bf3
  sha: ba7bf757be8004d9dbffbe583396620cfcbed788
  size: 25490
nginx/nginx-0.8.54.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b104fbd4f1e1f6fa
  sha: 4d63c35b8974dba42cc62dd5046ae89df3528e34
  size: 650001
nginx/nginx_upload_module-2.2.0.tar.gz:
  object_id: rest/objects/4e4e78bca11e121004e4e7d511f82104fbd4f1f40a30
  sha: 93d6e83e613a0ce2ed057a434b344fa1b6609b47
  size: 25796
nginx/pcre-8.12.tar.gz:
  object_id: rest/objects/4e4e78bca51e121204e4e86ee8e2c904fbd4f203c8e7
  sha: b3ab606864606c9f980045653554bf4a12cadde2
  size: 1316863
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca11e122004e4e8ec64843104fbd4f219f4b7
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76304fbd4f269d377
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca61e121004e4e7d51d950e04fbd4f2ca2d89
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
powerdns/pdns-static_3.0.1-1_amd64.deb:
  object_id: rest/objects/4e4e78bca41e121204e4e86ee5392104fbd4f33887f0
  sha: 5f6cc7572479ea1ab21b517e6f79ad921623b489
  size: 11180332
redis/redis-2.2.4.tar.gz:
  object_id: rest/objects/4e4e78bca41e122004e4e8ec65f67f04fbd4f388786e
  sha: 063e6e9f615ceda664d0691a6ea59befb22ebc40
  size: 447499
ruby/bundler-1.0.12.gem:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae04fbd4f39d1431
  sha: 4acd470b77d0d8f66440f137c918464b3e967a42
  size: 160768
ruby/rake-0.8.7.gem:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fbd4f3ae519a
  sha: 91daad079d404b68a7dd179716b9fdd0c195144c
  size: 104960
ruby/ruby-1.8.7-p302.tar.bz2:
  object_id: rest/objects/4e4e78bca31e121204e4e86ee3969204fbd4f3c13434
  sha: d93bd2f1099f3473b496cda2422b27a8da2beb00
  size: 4184764
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407704fbd4f3e88d6f
  sha: 6a482bc07239b37bcadf68dda63c65d20dc19ebe
  size: 11158935
ruby/rubygems-1.7.2.tgz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76304fbd4f43e7a27
  sha: d878ae52f40eb71e59708afc57303172f0327fad
  size: 245606
ruby/bundler-1.2.1.gem:
  object_id: rest/objects/4e4e78bca51e122204e4e9863f28f3050aa6aab5548d
  sha: 0cbe6ad7a41f064d6c11c1058465fffb1bd58069
  size: 226816
ruby/rubygems-1.8.24.tgz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f553050aa6aad74ec8
  sha: 30f27047e74f7943117736a0d3e224994fee0905
  size: 380101
golang/go1.0.3.src.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b1050b511f8d9fe0
  sha: 1a67293c10d6c06c633c078a7ca67e98c8b58471
  size: 7404849
nginx/nginx-1.4.1.tar.gz:
  object_id: 963ead7f-fb2f-4a6b-83be-5d3d25afafd9
  sha: !binary |-
    OWM3MjgzODk3MzU3MjMyMzUzNWRhZTEwZjRlNDEyZDY3MWIyN2E3ZQ==
  size: 767107
nginx/pcre-8.32.tar.gz:
  object_id: 9af63f91-2ad7-4894-a8ca-cb036211ce3f
  sha: !binary |-
    OTIyNmE1MzM2ZTA0YmJkY2FiMWQ5NGY3NDEzMTUzYWZiZjRhYmY2YQ==
  size: 1790055
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f04fb68b2898dd0
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
  size: 34179263
genisoimage/cdrkit-1.1.11.tar.gz:
  object_id: bb61a16c-6078-4e18-9c1f-9c2d6f056cd6
  sha: !binary |-
    M2Y3ZGRjMDZkYjAyNzI5NDJlMWE0Y2Q5OGMzYzk2NDYyZGY3NzM4Nw==
  size: 1445133
ruby/ruby-1.9.3-p484.tar.gz:
  object_id: e2ef4d3e-59bd-4c7c-aba2-e9df6d2a9c7e
  sha: !binary |-
    NmFlODBmNDI0OTY4YjVjZTY2MWVlOWIyYmVlMWMyMWFkYzllZTY3Yw==
  size: 12576996
ruby/rubygems-2.1.11.tgz:
  object_id: a949ba57-c5f8-43a1-a3e5-44faf1ab3b88
  sha: !binary |-
    Y2EzMDMzNDMyY2FlMjhkZWI3Y2VkNzljZGEyNzFjYjI5MmI3MGU1OQ==
  size: 367166
ruby/bundler-1.5.2.gem:
  object_id: 7ab3bb7d-9ed5-4ff7-ae53-22ad6cac7342
  sha: !binary |-
    NzhhOWZlMTE2MTQwNzc3OGY0MzdmYWUzOWNiNWFjNTExMjdmNDYzNQ==
  size: 286208
